config/routes.rb
IntuitSprint::Application.routes.draw do
  resources :transactions

  resources :pools

  resources :users

  resources :businesses

end

app/models/pool.rb
class Pool < ActiveRecord::Base
  has_many :transactions
  has_many :users, :through => :transactions
end

app/controllers/pools_controller.rb
class PoolsController < ApplicationController
  # GET /pools
  # GET /pools.xml
  def index
    @pools = Pool.all

    respond_to do |format|
      format.html # index.html.erb
      format.js  { render :json => @pools }
    end
  end

  # GET /pools/1
  # GET /pools/1.xml
  def show
    @pool = Pool.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @pool }
    end
  end

  # GET /pools/new
  # GET /pools/new.xml
  def new
    @pool = Pool.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @pool }
    end
  end

  # GET /pools/1/edit
  def edit
    @pool = Pool.find(params[:id])
  end

  # POST /pools
  # POST /pools.xml
  def create
    @pool = Pool.new(params[:pool])

    respond_to do |format|
      if @pool.save
        format.html { redirect_to(@pool, :notice => 'Pool was successfully created.') }
        format.xml  { render :xml => @pool, :status => :created, :location => @pool }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @pool.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /pools/1
  # PUT /pools/1.xml
  def update
    @pool = Pool.find(params[:id])

    respond_to do |format|
      if @pool.update_attributes(params[:pool])
        format.html { redirect_to(@pool, :notice => 'Pool was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @pool.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /pools/1
  # DELETE /pools/1.xml
  def destroy
    @pool = Pool.find(params[:id])
    @pool.destroy

    respond_to do |format|
      format.html { redirect_to(pools_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/pools_helper.rb
module PoolsHelper
end

app/views/pools/_form.html.erb
<%= form_for(@pool) do |f| %>
  <% if @pool.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pool.errors.count, "error") %> prohibited this pool from being saved:</h2>

      <ul>
      <% @pool.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :category %><br />
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :free_money %><br />
    <%= f.text_field :free_money %>
  </div>
  <div class="field">
    <%= f.label :invested_money %><br />
    <%= f.text_field :invested_money %>
  </div>
  <div class="field">
    <%= f.label :return_rate %><br />
    <%= f.text_field :return_rate %>
  </div>
  <div class="field">
    <%= f.label :analytics_url %><br />
    <%= f.text_field :analytics_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pools/edit.html.erb
<h1>Editing pool</h1>

<%= render 'form' %>

<%= link_to 'Show', @pool %> |
<%= link_to 'Back', pools_path %>

app/views/pools/index.html.erb
<h1>Listing pools</h1>

<table>
  <tr>
    <th>Category</th>
    <th>Free money</th>
    <th>Invested money</th>
    <th>Return rate</th>
    <th>Analytics url</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pools.each do |pool| %>
  <tr>
    <td><%= pool.category %></td>
    <td><%= pool.free_money %></td>
    <td><%= pool.invested_money %></td>
    <td><%= pool.return_rate %></td>
    <td><%= pool.analytics_url %></td>
    <td><%= link_to 'Show', pool %></td>
    <td><%= link_to 'Edit', edit_pool_path(pool) %></td>
    <td><%= link_to 'Destroy', pool, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Pool', new_pool_path %>

app/views/pools/new.html.erb
<h1>New pool</h1>

<%= render 'form' %>

<%= link_to 'Back', pools_path %>

app/views/pools/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>category:</b>
  <%= @pool.category %>
</p>

<p>
  <b>Free money:</b>
  <%= @pool.free_money %>
</p>

<p>
  <b>Invested money:</b>
  <%= @pool.invested_money %>
</p>

<p>
  <b>Return rate:</b>
  <%= @pool.return_rate %>
</p>

<p>
  <b>Analytics url:</b>
  <%= @pool.analytics_url %>
</p>


<%= link_to 'Edit', edit_pool_path(@pool) %> |
<%= link_to 'Back', pools_path %>