config/routes.rb
IntuitSprint::Application.routes.draw do
  resources :transactions

  resources :pools

  resources :users

  resources :businesses

end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  # GET /businesses
  # GET /businesses.xml
  def index
    @businesses = Business.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @businesses }
      format.js  { render :json => @businesses }
    end
  end

  # GET /businesses/1
  # GET /businesses/1.xml
  def show
    @business = Business.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @business }
    end
  end

  # GET /businesses/new
  # GET /businesses/new.xml
  def new
    @business = Business.new

    respond_to do |format|
      format.html # new.html.erb
      format.json  { render :json => @business }
    end
  end

  # GET /businesses/1/edit
  def edit
    @business = Business.find(params[:id])
  end

  # POST /businesses
  # POST /businesses.xml
  def create
    @business = Business.new(params[:business])

    respond_to do |format|
      if @business.save
        format.html { redirect_to(@business, :notice => 'Business was successfully created.') }
        format.xml  { render :xml => @business, :status => :created, :location => @business }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @business.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /businesses/1
  # PUT /businesses/1.xml
  def update
    @business = Business.find(params[:id])

    respond_to do |format|
      if @business.update_attributes(params[:business])
        format.html { redirect_to(@business, :notice => 'Business was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @business.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /businesses/1
  # DELETE /businesses/1.xml
  def destroy
    @business = Business.find(params[:id])
    @business.destroy

    respond_to do |format|
      format.html { redirect_to(businesses_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/businesses_helper.rb
module BusinessesHelper
end

app/views/businesses/_form.html.erb
<%= form_for(@business) do |f| %>
  <% if @business.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@business.errors.count, "error") %> prohibited this business from being saved:</h2>

      <ul>
      <% @business.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <br />
  <table border="0">
    <tr>
    <td><%= f.label :user_id %>:</td>
    <td><%= f.text_field :user_id %></td>
    </tr>
    <tr>
    <td>Business Title:</td>
    <td><%= f.text_field :title %></td>
    </tr>
    <tr>
    </tr>
    <tr>
    <td><%= f.label :funding_target %>:</td>
    <td><%= f.text_field :funding_target %></td>
    </tr>
    
  </table>
  <br />
  <%= f.label :description %>:<br />
  <%= f.text_area :description,  :cols => 38, :rows => 10%>
    
    
  <div class="field">
    <%= f.label :attachment_url %><br />
    <%= f.text_field :attachment_url %>
  </div>
  <div class="field">
    <%= f.label :votes %><br />
    <%= f.text_field :votes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/businesses/edit.html.erb
<h1>Editing business</h1>

<%= render 'form' %>

<%= link_to 'Show', @business %> |
<%= link_to 'Back', businesses_path %>

app/views/businesses/index.html.erb
<h1>Listing businesses</h1>

<table>
  <tr>
    <th>User</th>
    <th>Title</th>
    <th>Description</th>
    <th>Video url</th>
    <th>Photo url</th>
    <th>Funding target</th>
    <th>Attachment url</th>
    <th>Votes</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @businesses.each do |business| %>
  <tr>
    <td><%= business.user_id %></td>
    <td><%= business.title %></td>
    <td><%= business.description %></td>
    <td><%= business.video_url %></td>
    <td><%= business.photo_url %></td>
    <td><%= business.funding_target %></td>
    <td><%= business.attachment_url %></td>
    <td><%= business.votes %></td>
    <td><%= link_to 'Show', business %></td>
    <td><%= link_to 'Edit', edit_business_path(business) %></td>
    <td><%= link_to 'Destroy', business, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Business', new_business_path %>

app/views/businesses/new.html.erb
<h1>Start your business!</h1>

<%= render 'form' %>

<%= link_to 'Back', businesses_path %>

app/views/businesses/show.html.erb
<p id="notice"><%= notice %></p>


<h1><%= @business.title %></h1>
<br />
<div id="video_box">
  <iframe title="YouTube video player" width="480" height="390" src="http://www.youtube.com/embed/<%= @business.video_url %>" frameborder="0" allowfullscreen></iframe>
</div>

<div id="business_info_box">
  <span style="font-weight:bold; font-size:15px;">Funding Target:</span> <%= @business.funding_target %>
  <br />
  <br />
  <%= @business.description %>
</div>

<br />
<br />
<div id="business_description">

<p>
  <b>user:</b>
  <%= @business.user_id %>
</p>



<p>
  <b>Description:</b>
  
</p>

<p>
  <b>Video url:</b>
  
</p>

<p>
  <b>Photo url:</b>
  <%= @business.photo_url %>
</p>

<p>
  <b>Funding target:</b>
  
</p>

<p>
  <b>Attachment url:</b>
  <%= @business.attachment_url %>
</p>

<p>
  <b>Votes:</b>
  <%= @business.votes %>
</p>
</div>


<%= link_to 'Edit', edit_business_path(@business) %> |
<%= link_to 'Back', businesses_path %>